### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by AntiWarforever** [yanpaing007/DropsBot#2]
I use Windscribe vpn & sometimes after several hour get this error 
```
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 788, in _loop_self_reading
  File "asyncio\windows_events.py", line 837, in _poll
  File "asyncio\windows_events.py", line 462, in finish_recv
ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
```

after this error don't again reconnect bot
i want reconnect everytime this error coming
what is this? how can fix?
have a solation?
I have the same problem with all bots, when the internet is disconnected and reconnected, the bot does not connect to the internet again (see photo)
![Capture3](https://github.com/user-attachments/assets/ef991a8a-d004-43a5-b380-4374038103da)

**Comment by yanpaing007** [comment]
I will roll out an update soon,hope that will solve your issue
